name: Setup Godot
description: Setup Godot dependencies.
runs:
  using: "composite"
  steps:

    - name: Installing Linux dependencies
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: sudo apt-get install -y pulseaudio xvfb x11-xserver-utils mesa-vulkan-drivers

    - name: Starting X11 server on :0
      if: ${{ runner.os == 'Linux' }}
      shell: bash
      run: xset -q || /bin/bash -c "sudo Xvfb -ac :0 -screen 0 1920x1080x24 > /dev/null 2>&1 &"
      env:
        DISPLAY: ":0"

    - name: Check that X11 server is running
      if: ${{ runner.os == 'Linux' }}
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 1
        max_attempts: 5
        command: /bin/bash -c "xset -q > /dev/null 2>&1"
      env:
        DISPLAY: ":0"

    - name: Starting dummy sound device
      if: ${{ runner.os == 'Linux' }}
      uses: nick-fields/retry@v3
      with:
        timeout_minutes: 1
        max_attempts: 3
        command: pulseaudio --check || pulseaudio -D
